### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by tfausak**
This pull request upgrades the dependencies to allow base 4.9 (GHC 8.0.1) and HUnit 1.3. With these changes, this project can be built with all Stackage snapshots from LTS 3 to the current nightly. It can also be built with the GHC 8.0.1 release candidate. 

If desired, I can split this into two pull requests: One for HUnit and another for base.

### CODE REVIEW

**Comment by tfausak** [comment]
Now that [GHC 8.0.1 is available](https://ghc.haskell.org/trac/ghc/blog/ghc-8.0.1-released), this would be especially nice to have.

**Comment by tfausak** [comment]
Thanks!

**Comment by jcristovao** [comment]
Thanks!
I will try to upload it to hackage tomorrow

**Comment by tfausak** [comment]
Any chance you can get a new version uploaded? The most recent Stackage snapshot uses GHC 8.0.1, which uses base 4.9. That means newtype-generics isn't included in the snapshot.

**Pull request merged**
